apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-kgzg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-kgzg@sha256:67186aff5ff1766e722907d5feabf8b14c4b7ba24ffa53834bc581bf244a451e
        name: my-python
        resources: {}
status: {}
